import Head from "next/head";
import SideNavbar from "../components/SideNavbar";
import TableBar from "../components/Table/TableBar";
import { NextUIProvider } from "@nextui-org/react";

export default function Home() {
  return (
    <div>
      <div className="bg-blue-800">
        <Head>
          <title>Kentron</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/pro.ico" />
        </Head>
        <SideNavbar />
      </div>
      <NextUIProvider>
        <div className="ml-64 p-4"> {/* Add margin and padding to create space */}
          <TableBar />
        </div>
      </NextUIProvider>
    </div>
  );
}
